language: php

os: linux
dist: xenial

addons:
  postgresql: "9.6"

services:
  - mysql
  - postgresql

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

php:
  - 7.2
  - 7.3

env:
  # Unit tests and behat tests against full matrix (Implicit "test" stage).
  global:
    - MOODLE_BRANCH=MOODLE_37_STABLE DB=mysqli
    - MOODLE_BRANCH=MOODLE_38_STABLE DB=mysqli
    - MOODLE_BRANCH=MOODLE_39_STABLE DB=mysqli
    - MOODLE_BRANCH=MOODLE_10_STABLE DB=mysqli
    - MOODLE_BRANCH=master DB=mysqli

jobs:
  include:
    # Prechecks against one configuration (Moodle, PHP, DB) only.
    - stage: prechecks
      php: 7.3
      env: DB=pgsql MOODLE_BRANCH=MOODLE_310_STABLE
      install:
      - moodle-plugin-ci install
      script:
      - moodle-plugin-ci phplint
      - moodle-plugin-ci phpcpd
      - moodle-plugin-ci phpmd
      - moodle-plugin-ci codechecker
      - moodle-plugin-ci validate
      - moodle-plugin-ci savepoints
      - moodle-plugin-ci mustache
      - moodle-plugin-ci grunt || true
      - moodle-plugin-ci phpdoc || true

before_install:
  - phpenv config-rm xdebug.ini
  - cd ../..
  - composer create-project -n --no-dev --prefer-dist moodlehq/moodle-plugin-ci ci ^3
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"
  - export BEHAT=no

install:
  - moodle-plugin-ci install

script:
  - moodle-plugin-ci phpunit
  - if [ $BEHAT == 'yes' ]; then
        moodle-plugin-ci behat || travis_terminate 1;
    fi

stages:
  - prechecks
  - test

notifications:
  email:
    on_success: never   # default: change
    on_failure: always  # default: always
