language: php

addons:
  postgresql: "9.6"

services:
  - mysql
  - postgresql
  - docker

notifications:
  email:
    on_success: never # default: change
    on_failure: always # default: always

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

php:
  - 7.2
  - 7.3

env:
  global:
    - MOODLE_BRANCH=MOODLE_37_STABLE DB=mysqli
    - MOODLE_BRANCH=MOODLE_38_STABLE DB=mysqli
#     - MOODLE_BRANCH=MOODLE_39_STABLE DB=mysqli
    - MOODLE_BRANCH=master
  matrix:
#     - DB=pgsql
    - DB=mysqli

before_install:
  - phpenv config-rm xdebug.ini
  - nvm install node
  - nvm use node
  - cd ../..
  - composer create-project -n --no-dev --prefer-dist blackboard-open-source/moodle-plugin-ci ci ^2
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"
  - docker run -d -p 127.0.0.1:4444:4444 --net=host -v /dev/shm:/dev/shm selenium/standalone-firefox:3

jobs:
  include:
    # Prechecks against one configuration (Moodle, PHP, DB) only.
    - stage: prechecks
      php: 7.3
      env: DB=pgsql MOODLE_BRANCH=MOODLE_38_STABLE
      install:
      - moodle-plugin-ci install --no-init
      script:
      - moodle-plugin-ci phplint
      - moodle-plugin-ci phpcpd
      - moodle-plugin-ci phpmd
      - moodle-plugin-ci codechecker
      - moodle-plugin-ci validate
      - moodle-plugin-ci savepoints
      - moodle-plugin-ci mustache
      - moodle-plugin-ci grunt
      - moodle-plugin-ci phpdoc

# Unit tests and behat tests against full matrix (Implicit "test" stage).
install:
  - moodle-plugin-ci install

script:
  - moodle-plugin-ci phpunit
  - moodle-plugin-ci behat

stages:
  - prechecks
  - test
